#!/usr/bin/env python
""" Execute a task and print the response on stdout.
"""
import sys
import json
import time

import bashtasks as bashtasks_mod

arguments = sys.argv

if len(arguments) < 2:
    print "Usage: python client_cli.py <COMMAND> [ARGUMENTS...]"
    sys.exit(0)


def currtimemillis():
    return int(round(time.time() * 1000))

start_ts = currtimemillis()

bashtasks = bashtasks_mod.init()
response_msg = bashtasks.execute_task(arguments[1:])

total_time = currtimemillis() - response_msg['request_ts']
command_time = response_msg['post_command_ts'] - response_msg['pre_command_ts']
print('==========================================================================================')
print("received response: returncode : " + str(response_msg['returncode']))
print("                   command    : " + ' '.join(response_msg['command']))
print("                   executor   : " + response_msg['executor_name'])
print("                   stdout     : ")
print('__________________________________________________________________________________________')
print(response_msg['stdout'])
print('__________________________________________________________________________________________')
print("Time:")
print("    total   : " + str(total_time) + "ms.")
print("    command : " + str(command_time) + "ms.")
print('==========================================================================================')
print(json.dumps(response_msg, indent=2))

sys.exit(0)
