#!/usr/bin/env python
""" Execute a task and print the response on stdout.
"""
import sys
import json
import time

import bashtasks as bashtasks_mod

arguments = sys.argv

if len(arguments) < 2:
    print "Usage: python client_cli.py <COMMAND> [ARGUMENTS...]"
    sys.exit(0)


def currtimemillis():
    return int(round(time.time() * 1000))

start_ts = currtimemillis()

bashtasks = bashtasks_mod.init()
response_msg = bashtasks.execute_task(arguments[1:])

print('==========================================================================================')
print("received response: returncode :", response_msg['returncode'])
print("                   command    :", ' '.join(response_msg['command']))
print("                   request_ts :", response_msg['request_ts'])
print("                   stdout     :")
print('__________________________________________________________________________________________')
print(response_msg['stdout'])
print('__________________________________________________________________________________________')
print("Time:")
print("     total   : ", currtimemillis() - response_msg['request_ts'], "ms.")
print("     command : ", response_msg['post_command_ts'] - response_msg['pre_command_ts'], "ms.")
print('==========================================================================================')

sys.exit(0)
